name: 🧠 Visual PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    name: 🧠 Analyze PR and Post Diagrams
    runs-on: ubuntu-latest

    env:
      CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper diff analysis

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'  # Cache npm dependencies
          
      - name: 📦 Install Dependencies
        run: npm install
        
      - name: 🧠 Run PR Checker
        run: node src/index.js
        
      - name: 📊 Upload Artifacts (if available)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pr-review-artifacts
          path: |
            *.png
            *.md
          retention-days: 7
